
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Mawada Nagi
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    
    int players = 2;
    int buttonused[] = {0,0,0,0,0,0,0,0,0};
    int X_won[] = {0,0,0,0,0,0,0,0,0};
    int O_won[] = {0,0,0,0,0,0,0,0,0};
    int scoreX = 0;
    int scoreO = 0;
    
    boolean X_won()
    {
        
        if(X_won[0] == 1 && X_won[1] == 1 && X_won[2] == 1){
            Button1.setBackground(Color.CYAN);
            Button2.setBackground(Color.CYAN);
            Button3.setBackground(Color.CYAN);
            return true;
        }
        if(X_won[3] == 1 && X_won[4] == 1 && X_won[5] == 1){
            Button4.setBackground(Color.CYAN);
            Button5.setBackground(Color.CYAN);
            Button6.setBackground(Color.CYAN);
            return true;
        }
        if(X_won[6] == 1 && X_won[7] == 1 && X_won[8] == 1){
            Button7.setBackground(Color.CYAN);
            Button8.setBackground(Color.CYAN);
            Button9.setBackground(Color.CYAN);
            return true;
        }
        if(X_won[0] == 1 && X_won[3] == 1 && X_won[6] == 1){
            Button1.setBackground(Color.CYAN);
            Button4.setBackground(Color.CYAN);
            Button7.setBackground(Color.CYAN);
            return true;
        }
        if(X_won[1] == 1 && X_won[4] == 1 && X_won[7] == 1){
            Button2.setBackground(Color.CYAN);
            Button5.setBackground(Color.CYAN);
            Button8.setBackground(Color.CYAN);
            return true;
        }
        if(X_won[2] == 1 && X_won[5] == 1 && X_won[8] == 1){
            Button3.setBackground(Color.CYAN);
            Button6.setBackground(Color.CYAN);
            Button9.setBackground(Color.CYAN);
            return true;
        }
        if(X_won[0] == 1 && X_won[4] == 1 && X_won[8] == 1){
            Button1.setBackground(Color.CYAN);
            Button5.setBackground(Color.CYAN);
            Button9.setBackground(Color.CYAN);
            return true;
        }
        if(X_won[2] == 1 && X_won[4] == 1 && X_won[6] == 1){
            Button3.setBackground(Color.CYAN);
            Button5.setBackground(Color.CYAN);
            Button7.setBackground(Color.CYAN);
            return true;
        }
        return false;
    }
    
     boolean O_won(){
        if(O_won[0] == 1 && O_won[1] == 1 && O_won[2] == 1){
            Button1.setBackground(Color.CYAN);
            Button2.setBackground(Color.CYAN);
            Button3.setBackground(Color.CYAN);
            return true;
        }
        if(O_won[3] == 1 && O_won[4] == 1 && O_won[5] == 1){
            Button4.setBackground(Color.CYAN);
            Button5.setBackground(Color.CYAN);
            Button6.setBackground(Color.CYAN);
            return true;
        }
        if(O_won[6] == 1 && O_won[7] == 1 && O_won[8] == 1){
            Button7.setBackground(Color.CYAN);
            Button8.setBackground(Color.CYAN);
            Button9.setBackground(Color.CYAN);
            return true;
        }
        if(O_won[0] == 1 && O_won[3] == 1 && O_won[6] == 1){
            Button1.setBackground(Color.CYAN);
            Button4.setBackground(Color.CYAN);
            Button7.setBackground(Color.CYAN);
            return true;
        }
        if(O_won[1] == 1 && O_won[4] == 1 && O_won[7] == 1){
            Button2.setBackground(Color.CYAN);
            Button5.setBackground(Color.CYAN);
            Button8.setBackground(Color.CYAN);
            return true;
        }
        if(O_won[2] == 1 && O_won[5] == 1 && O_won[8] == 1){
            Button3.setBackground(Color.CYAN);
            Button6.setBackground(Color.CYAN);
            Button9.setBackground(Color.CYAN);
            return true;
        }
        if(O_won[0] == 1 && O_won[4] == 1 && O_won[8] == 1){
            Button1.setBackground(Color.CYAN);
            Button5.setBackground(Color.CYAN);
            Button9.setBackground(Color.CYAN);
            return true;
        }
        if(O_won[2] == 1 && O_won[4] == 1 && O_won[6] == 1){
            Button3.setBackground(Color.CYAN);
            Button5.setBackground(Color.CYAN);
            Button7.setBackground(Color.CYAN);
            return true;
        }
        return false;
    }
  
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PlayerO = new javax.swing.JButton();
        PlayerX = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        restart = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 102, 204));

        Button8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(0, 153, 204));

        PlayerO.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        PlayerO.setText("0");

        PlayerX.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        PlayerX.setText("0");
        PlayerX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerXActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 38)); // NOI18N
        jLabel5.setText("Player X:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 38)); // NOI18N
        jLabel6.setText("Player O:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlayerX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlayerX, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlayerO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37))
        );

        Button5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button1.setForeground(new java.awt.Color(204, 0, 0));
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button3.setForeground(new java.awt.Color(204, 0, 0));
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(0, 153, 204));

        restart.setFont(new java.awt.Font("Snap ITC", 1, 16)); // NOI18N
        restart.setForeground(new java.awt.Color(204, 0, 0));
        restart.setText("PLAY AGAIN!");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Snap ITC", 1, 16)); // NOI18N
        reset.setForeground(new java.awt.Color(204, 0, 0));
        reset.setText("RESET!");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Snap ITC", 1, 16)); // NOI18N
        Exit.setForeground(new java.awt.Color(204, 0, 0));
        Exit.setText("EXIT!");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(Button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 100, 133));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe Game");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        
        if(buttonused[7] == 0){
            if(players%2 == 0){
                players++;
                Button8.setText("X");
                buttonused[7] = 1;
                X_won[7] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button8.setText("O");
                buttonused[7] = 1;
                O_won[7] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        }
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        
        if(buttonused[8] == 0){
            if(players%2 == 0){
                players++;
                Button9.setText("X");
                buttonused[8] = 1;
                X_won[8] = 1;
                

                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button9.setText("O");
                buttonused[8] = 1;
                O_won[8] = 1;
                

                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        }
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        
         if(buttonused[6] == 0){
            if(players%2 == 0){
                players++;
                Button7.setText("X");
                buttonused[6] = 1;
                X_won[6] = 1;

                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button7.setText("O");
                buttonused[6] = 1;
                O_won[6] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        }
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        
        if(buttonused[5] == 0){
            if(players%2 == 0){
                players++;
                Button6.setText("X");
                buttonused[5] = 1;
                X_won[5] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button6.setText("O");
                buttonused[5] = 1;
                O_won[5] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        }
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        
        if(buttonused[4] == 0){
            if(players%2 == 0){
                players++;
                Button5.setText("X");
                buttonused[4] =1;
                X_won[4] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button5.setText("O");
                buttonused[4] = 1;
                O_won[4] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        } 
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        
         if(buttonused[3] == 0){
            if(players%2 == 0){
                players++;
                Button4.setText("X");
                buttonused[3] = 1;
                X_won[3] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button4.setText("O");
                buttonused[3] = 1;
                O_won[3] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        }   
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        
        if(buttonused[0] == 0){
            if(players%2 == 0){
                players++;
                Button1.setText("X");
                buttonused[0] = 1;
                X_won[0] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button1.setText("O");
                buttonused[0] = 1;
                O_won[0] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        }
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        
        if(buttonused[2] == 0){
            if(players%2 == 0){
                players++;
                Button3.setText("X");
                buttonused[2] = 1;
                X_won[2] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button3.setText("O");
                buttonused[2] = 1;
                O_won[2] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        }
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed

         if(buttonused[1] == 0){
            if(players%2 == 0){
                players++;
                Button2.setText("X");
                buttonused[1] = 1;
                X_won[1] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
            
            }else{
                players++;
                Button2.setText("O");
                buttonused[1] = 1;
                O_won[1] = 1;
                
                
                if(X_won()){
                    scoreX++;
                    PlayerX.setText(String.valueOf(scoreX));
                    JOptionPane.showMessageDialog(rootPane, "Player X has won! ");
                }else if(O_won()){
                    scoreO++;
                    PlayerO.setText(String.valueOf(scoreO));
                    JOptionPane.showMessageDialog(rootPane, "Player O has won! ");
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "This Button is Already Used! ");
        }
    }//GEN-LAST:event_Button2ActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        
        Button1.setText("");
        Button2.setText("");
        Button3.setText("");
        Button4.setText("");
        Button5.setText("");
        Button6.setText("");
        Button7.setText("");
        Button8.setText("");
        Button9.setText("");
        
        Button1.setBackground(Color.LIGHT_GRAY);
        Button2.setBackground(Color.LIGHT_GRAY);
        Button3.setBackground(Color.LIGHT_GRAY);
        Button4.setBackground(Color.LIGHT_GRAY);
        Button5.setBackground(Color.LIGHT_GRAY);
        Button6.setBackground(Color.LIGHT_GRAY);
        Button7.setBackground(Color.LIGHT_GRAY);
        Button8.setBackground(Color.LIGHT_GRAY);
        Button9.setBackground(Color.LIGHT_GRAY);
        
        players = 2;
        for(int i = 0;i<9;i++){
            buttonused[i]=0;
        }
        for(int i = 0;i<9;i++){
            X_won[i]=0;
        }
        for(int i = 0;i<9;i++){
            O_won[i]=0;
        }
    }//GEN-LAST:event_restartActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        
        Button1.setText("");
        Button2.setText("");
        Button3.setText("");
        Button4.setText("");
        Button5.setText("");
        Button6.setText("");
        Button7.setText("");
        Button8.setText("");
        Button9.setText("");
        PlayerX.setText("0");
        PlayerO.setText("0");
        
        Button1.setBackground(Color.LIGHT_GRAY);
        Button2.setBackground(Color.LIGHT_GRAY);
        Button3.setBackground(Color.LIGHT_GRAY);
        Button4.setBackground(Color.LIGHT_GRAY);
        Button5.setBackground(Color.LIGHT_GRAY);
        Button6.setBackground(Color.LIGHT_GRAY);
        Button7.setBackground(Color.LIGHT_GRAY);
        Button8.setBackground(Color.LIGHT_GRAY);
        Button9.setBackground(Color.LIGHT_GRAY);
        
        
        players = 2;
        for(int i = 0;i<9;i++){
            buttonused[i]=0;
            X_won[i]=0;
            O_won[i]=0;
        }
    }//GEN-LAST:event_resetActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        
        if(JOptionPane.showConfirmDialog(rootPane, "Sure you want to Exit the Game? ", "Tic Tac Toe", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);  
        }
        
    }//GEN-LAST:event_ExitActionPerformed

    private void PlayerXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayerXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton Exit;
    private javax.swing.JButton PlayerO;
    private javax.swing.JButton PlayerX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton reset;
    private javax.swing.JButton restart;
    // End of variables declaration//GEN-END:variables
}
